const projectURL = 'https://acbwrtbrwzcppgurqjlf.supabase.co';

const apiKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjYndydGJyd3pjcHBndXJxamxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Njc1NTk3MDUsImV4cCI6MTk4MzEzNTcwNX0.f9QkQ2KzFOnpe4Vn3LxUFhQtadeTerf6csXFQra-cY0';
